In [3]:
!pip install numpy
!pip install pandas
!pip install matplotlib

 ### NOTE - python numpy code does not support GPU but by using numba and by using pytorch we can implement that

### We'll cover a few categories of basic array manipulations here:

1 - Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays

2 - Indexing of arrays: Getting and setting the value of individual array elements

3 - Slicing of arrays: Getting and setting smaller subarrays within a larger array

4 - Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [21]:
import numpy as np

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [22]:
#print(x1)
#print(x2)
print(x3)

[[[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]

 [[3 4 1 2 9]
  [1 4 6 8 2]
  [3 0 0 6 0]
  [6 3 3 8 8]]

 [[8 2 3 2 0]
  [8 8 3 8 2]
  [8 4 3 0 4]
  [3 6 9 8 0]]]


In [23]:
#by using itemsize we can get size of array 

print("itemsize:", x3.itemsize, "bytes")

itemsize: 8 bytes


#### Array Indexing

In [24]:
x1

array([4, 3, 4, 4, 8, 4])

In [25]:
x1[0]

4

In [27]:
# To index from the end of the array, you can use negative indices:

In [28]:
x1[-2]

8

In [30]:
# In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:   

In [31]:
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [32]:
x2[0, 0]

3

In [34]:
# Values can also be modified using any of the above index notation:

In [35]:
x2[0, 0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

### Array Slicing

In [37]:
# Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character.

In [38]:
# One-dimensional subarrays

In [40]:
x1[:3]

array([4, 3, 4])

In [41]:
x1[4:7]  # middle sub-array

array([8, 4])

In [43]:
x1[1::2]  # every other element, starting at index 1

array([3, 4, 4])

In [44]:
#Multi-dimensional subarrays

In [45]:
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [46]:
x2[:2, :3]  # two rows, three columns

array([[12,  7,  5],
       [ 0,  1,  5]])

### Array Concatenation and Splitting

In [47]:
# All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. 

In [48]:
# Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [50]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [51]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [53]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [54]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [55]:
# Splitting of arrays

In [57]:
#The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points

In [58]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [59]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [61]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
